name: Deploy Docusaurus

on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - '*'  # Permite deploys a partir de qualquer branch em pull requests
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install and Build
      run: |
        cd docs
        npm ci
        npm run build
        mv build ../build

    - name: Setup Pages
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/configure-pages@v3

    - name: Upload artifact
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/upload-pages-artifact@v2
      with:
        path: ../build

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      id: deployment
      uses: actions/deploy-pages@v2
